### PR TITLE
Snowflake support 

### LINKED ISSUE #265: Support for the Snowflake Cloud Data Platform
# Support for the Snowflake Cloud Data Platform

## Introduction

Hello everyone! In our project, called CLADE, we are analysing and comparing the features of current **data lakehouse** platforms, specifically using **Databricks** and **Snowflake**. Databricks uses Delta as its default table format and Snowflake has recently added support for [Iceberg Tables](https://docs.snowflake.com/en/user-guide/tables-iceberg).

While researching these data formats we discovered LST-Bench, and wanted to use it to measure the efficiency of Delta in Databricks and Iceberg in Snowflake. For the latter platform we need to add specific SQL queries and yaml files in the `run` folder. We are pleased to offer our support for this project by providing support for Snowflake.

## New run configuration

We suggest a new run folder for Snowflake with its own `config` folder containing the sample yaml files and a `scripts` folder containing the necessary sql statements. For the connection to Snowflake it is as simple as adding the corresponding [JDBC Driver](https://docs.snowflake.com/en/developer-guide/jdbc/jdbc) to `pom.xml`.

Scripts can have two build options. One to use the Snowflake default tables and the other one for the new Iceberg tables. The other tasks will be adapted to Snowflake syntax, for example with the use of Stages for data loading.

## Limitations

It is not possible to run the **Optimise task** on Snowflake Managed Iceberg tables. The REFRESH function is only available for externally managed tables, for example in AWS Glue (see [documentation](https://docs.snowflake.com/en/sql-reference/sql/alter-iceberg-table)). For Snowflake Managed Iceberg Tables, the metadata refresh is coordinated internally by Snowflake. If you try to use Refresh on it, the next error is displayed:

`ALTER command failed. The provided table must be an Iceberg table with an external catalog integration to perform the command ICEBERG_TABLE_REFRESH. The type of table ICEBERG_TABLE is MANAGED`

Therefore, we can only run the longevity, concurrency and time travel workloads. In the case of concurrency, the Optimise functions can be replaced by Data Mainteance functions.

---

Finally, just remember that we are happy to develop this support for Snowflake following the previous approach and your feedback, which is welcome.

### PR DESCRIPTION
**Pull request by agr17**
This is a proposal to add snowflake support to LST-Bench. These are the main changes:

- Add snowflake-jdbc to pom.xml
- Add a snowflake folder in the `run` folder.
- Edit `src/main/java/com/microsoft/lst_bench/common/SessionExecutor.java` to add time travel in snowflake single_user.

With the current content of this PR you can run all workloads for Snowflake. For the time being, no documentation (sample yaml files are available) or tests have been added, I prefer to wait for your feedback and recommendations.

Fix #265

### CODE REVIEW

**Comment by agr17** [comment]
@microsoft-github-policy-service agree company="Universidade da Coruña, A Coruña, Spain"

**Comment by jcamachor** [comment]
Thanks, @agr17 ! Structure looks good to me and is consistent with the implementation for other engines such as Spark and Trino.
I think you currently evaluate on native tables. Do you plan to add support for Iceberg tables as well? I think the syntax for that would be `CREATE ICEBERG TABLE`, so it might be easy to do it by passing a config value--empty for native tables and `ICEBERG` for Iceberg tables.
Also, small nit: please update the README.md file to reflect the new profile in the pom.xml file.

**Comment by agr17** [comment]
Hi @jcamachor , thanks for your feedback! Yes, I was planning to add support for Iceberg tables, my idea was to add it in another Issue/PR.

I had done it, but it is not enough to change one parameter. The data types in Iceberg tables are different from Snowflake types (see https://docs.snowflake.com/en/user-guide/tables-iceberg-data-types). So I created a `build_iceberg` folder with the necessary SQL statements and added it to a task_template in `library.yaml` called build_iceberg. Additional parameters are required, `external_volume`, which is needed in Snowflake to create Iceberg tables, and `base_location`, which specifies the folder on the `external_volume` where the table should be created. 

Iceberg table support is available in commit https://github.com/microsoft/lst-bench/pull/310/commits/e01a7962b4934e33601fd4c12d6595e6fe2dfaa5 (sorry for the name of the commit, it was an error). There are the `build_iceberg` folder, the corresponding tasks in `library.yaml` and the new parameters for the iceberg tables (exvol and base_location) in `sample_experiment_config.yaml`. This was done in a preliminary way, if you prefer a different approach to be in line with the rest of the project, I'm open to any changes.

**Comment by jcamachor** [comment]
@agr17 , this looks good, thanks! (Given the current LST-Bench framework, I do not think there is a better approach.) Since the SQL for the second step (inserting into the tables) is the same in both native and Iceberg, you might consider using a single copy of that step to reduce some of the duplication.

**Comment by agr17** [comment]
Hi @jcamachor . I have fixed the code redundancy using just one build folder with two subfolders, one for native tables and another for iceberg tables. The insert queries are the same files for both in the main build folder.

**Review by jcamachor — APPROVED** [review]

**Comment by jcamachor** [comment]
Merged to main, thanks for your contribution @agr17 !

**Pull request merged**
