### PR TITLE
Adds support for JDBC Fabric endpoints

### PR DESCRIPTION
**Pull request by netonjm**
This PR adds driver support to connect any Fabric Database using JDBC connector

### CODE REVIEW

**Review by anjagruenheid — APPROVED** [review]

**Comment by ashvina** [comment]
Thanks for the PR. However, I think the PR title is not addressed by the changes. I believe adding the dependencies is not sufficient. Supporting Fabric JDBC endpoints would likely need new scripts and configs. If so, could you please share some details about how specific changes and tests you plan to commit.

**Review by ashvina — CHANGES_REQUESTED** [review]
Thanks for the PR. However, I think the PR title is not addressed by the changes. I believe adding the dependencies is not sufficient. Supporting Fabric JDBC endpoints would likely need new scripts and configs. If so, could you please share some details about how specific changes and tests you plan to commit.

**Comment by jcamachor** [comment]
Thanks for your contribution @netonjm . To move this PR forward, could you add the new dependencies under a new maven profile (similar to what is done for Spark or Trino)? Also, as @ashvina mentioned, if you could share your plan to work on Fabric support and/or create GH issues for major contributions that you plan to make, that would be great.

**Comment by netonjm** [comment]
Sorry I miss this thread. @ashvina the plan is include other workloads like spark and others at some point (working on it), I will ping you with more details when we got something working.

@jcamachor added the new maven profile.

**Review by jcamachor — APPROVED** [review]

**Pull request merged**
